# Generated by Django 3.1.14 on 2022-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220406_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='kick_count',
            field=models.IntegerField(default=0),
        ),
    ]
