# Generated by Django 3.1.14 on 2022-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notificationweekly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_caution',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_danger',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_warning',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
