# Generated by Django 3.1.14 on 2022-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_centeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='center',
            name='telephone',
            field=models.CharField(max_length=16),
        ),
    ]
