# Generated by Django 3.1.14 on 2022-03-22 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.ForeignKey(db_column='center_id', on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'center_user',
            },
        ),
    ]
