# Generated by Django 3.1.14 on 2022-04-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20220324_0017'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_center',
            field=models.ForeignKey(db_column='target_center', on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
    ]
