# Generated by Django 3.1.14 on 2022-05-23 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_auto_20220523_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
